### ISSUE TITLE
Wikiのページ分割

### ISSUE THREAD

**Issue by equal-l2** [ab25cq/clover2#1]
こんにちは。

Wikiについてなのですが、1ページにすべての内容を入れると長くなってやや可読性に欠けるかと思います。
トピックごとに別ページに分けてみてはいかがでしょうか？

**Comment by ab25cq** [comment]
了解です。ちょっと今忙しいので、できませんが、またしておきますね。

**Comment by ab25cq** [comment]
すみません。ちょっと考えましたが、やはり、印刷しやすいように１ページのままにしておきます。ごめんなさい。ページが分割されていると印刷するときに面倒くさいので。僕自身よくライブラリのリファレンスなどを印刷するんですが、１ページに纏まっているページのほうが印刷しやすくて好きなんです、、、。一応目次からジャンプできるので、戻るボタンで目次に戻ったりしてみたら、楽に移動できますし、、、すみません。

**Comment by equal-l2** [comment]
印刷の利便性を考えるとたしかに1ページのほうが良いですね。
ご検討ありがとうございました。
