### ISSUE TITLE
コントリビューションの仕方についてまとめましょう

### ISSUE THREAD

**Issue by hsk** [ab25cq/clover2#10]
githubの使い方よく分かってないのですけど、プルリクエストを送りたいです。
ってときに困らないように、ここ見てってやつを作りましょう。
というか、書いて見てますのでこちらを参照するようお願いします。

https://github.com/ab25cq/clover2/wiki/contribution

**Comment by ab25cq** [comment]
ありがとうございます。

**Comment by ab25cq** [comment]
メニューに追加しておきました。
