### ISSUE TITLE
.が含まれるディレクトリ内での拡張子取得バク対策

### ISSUE THREAD

**Issue by hsk** [ab25cq/clover2#12]
PPAファイルを作ろうと思うと、バージョン番号付きのファイルを作ることになるのですが、

cclover2 /home/sakurai/git/clover2-3.1.8/code/TestDep.clcl
/home/sakurai/git/clover2-3.1.8/code/TestDep.clcl 1: undeclared variable class
と表示されてループになります。
原因を調べた所、拡張子取得のアルゴリズムに問題がありました。修正よろしくお願いします。

**Comment by ab25cq** [comment]
修正しました。まだ拡張子関連でstrstrを使っているところはバグがあるかもしれません。とりあえずは上記が動きます。

**Comment by ab25cq** [comment]
3.1.8bで対応しました。

**Comment by ab25cq** [comment]
strstrを使っている部分はなくしました。多分、大丈夫なはずです。version 3.1.8bで対応できていると思います。

**Comment by hsk** [comment]
ありがとうございます。確認しました！
