### ISSUE TITLE
sudo make uninstall && make && make testだとエラーになる。

### ISSUE THREAD

**Issue by hsk** [ab25cq/clover2#13]
PPAというかdebファイルを作る場合は configure && make && make test && make install
の順番でテストが行われます。現状make testはインストール前提になっているのでインストールされていない場合でもうごく対策をお願いします。

**Comment by ab25cq** [comment]
了解です。

**Comment by ab25cq** [comment]
対応しました。./configure && make && make test && make installの順でコンパイルできます。

**Comment by ab25cq** [comment]
version 3.1.8bで対応しています。

**Comment by hsk** [comment]
対応ありがとうございます。確認しました！
