### ISSUE TITLE
big endianでテストが成功しない

### ISSUE THREAD

**Issue by mtasaka** [ab25cq/clover2#16]
報告しておこうと思いますが、今のgit headで、big endianでテストが成功しません。

https://koji.fedoraproject.org/koji/taskinfo?taskID=24690531
ppc64. s390x:
```
ParserTest
code/main.cl 4: Buffer size is smaller than the size value of argument at System.read(code/main.cl 4)(code/ParserTest.clcl 5)(CLParser.clcl 308)(/builddir/build/BUILD/clover2-93d24a620cb730a5578a6be8cdd00a28d2cc53cd/File.clcl 432)(/builddir/build/BUILD/clover2-93d24a620cb730a5578a6be8cdd00a28d2cc53cd/File.clcl 446)
script file(code/main.cl) is abort
make: *** [Makefile:392: test] Error 1
```

**Comment by ab25cq** [comment]
了解です。確かlong longをint型２つでmemcpyしている部分があって
そこだけ、多分big endianでは動かないはずです。
キャスト部分はC言語が違いを吸収してくれますよね。なんかmfiler4とxyzshのときもやったような。
次のアップデートでは修正してみます。3.5.7で。ちょっとソースコードを確認してみます。

**Comment by ab25cq** [comment]
現在qemuでppcの環境が作れたのでデバッグ中です。思ったよりは難しいみたいでテストが通りません。
次のアップデートで修正したいと思います。

**Comment by ab25cq** [comment]
3.5.7で対応できたと思います。32bitのppcでは動いています。ちょっと64bitのppcでは環境が作れていないので、対応できたか分かりません。たぶん、大丈夫だと思いますが、もし動かなかったら教えてください。ちょっと時間が出来たら、ppc64の環境も作ってみます。

**Comment by ab25cq** [comment]
ppc64でも動作確認が取れました。

**Comment by mtasaka** [comment]
Fedora/kojiでもppc64, s390xで確認取れました。有難うございます。
