### ISSUE TITLE
オブジェクトファイル名の拡張子の統一をして消しやすくしてほしい

### ISSUE THREAD

**Issue by hsk** [ab25cq/clover2#4]
OCaml ですと、生成されるファイル名が *.cmi *.cmo *.cmx *.cma など統一された名前なので、様々なファイルを
 rm *.cm* で消すことが出来て便利です。

残念ながら cloverのコンパイル時に生成されるクラスファイル名とメインファイル名が現状は、.cloと.clclです。
これを例えば、.cloと.clocなどにしてもらうと、

rm *.clo*

で全て消すことが出来て便利ではないかと思います。

*.ocl *.occ でも良いのですがとにかく統一されていると便利だろうと思いますので、検討お願いします。

**Comment by ab25cq** [comment]
version 3.0.8で変更しました。rm \*.o\*で消すことができます。

**Comment by hsk** [comment]
ありがとうございます。確認しましたのでクローズしましょう
