### ISSUE TITLE
Javacのようにコンパイル時に必要なクラスファイルがない場合に、ソースがあればコンパイルしてください

### ISSUE THREAD

**Issue by hsk** [ab25cq/clover2#6]
Pull Request もした内容ですが、Javacは１つのJavaファイルを指定するだけで自動的に依存解析をして必要なファイルをすべて辿ってコンパイルしてくれて便利です。ghcなども辿ってくれます。

Clover2にも同様の機能があれば、便利でしょうし、コマンドラインで気軽に使ってもらうにはあったほうが良い機能だと思います。

実装方法

①コンパイル時にクラスファイルをロードしようとしたときにクラスファイルがなかったら、クラスファイルに対応するソースファイルをコンパイルするようにする。
②Dep1ファイルがDep2ファイルを参照し、Dep2ファイルがDep1ファイルを参照していると無限ループに陥るので依存の相互再帰がある場合は、その情報を何かしらの形で保存し再入チェックを行い、再入があった場合はエラーとする。
③system関数を使った場合はプロセス間の情報共有が必要になるのでファイルを用いてコンパイルするファイル名を記録する。ファイル名は絶対パスだったり、相対パスだったりするので、パス情報は消してファイル名だけで扱う。

以上のようにすることで依存情報を解析しながらコンパイルすることが出来ます。

**Comment by ab25cq** [comment]
了解です。今コミットしました。手直し中です。

**Comment by hsk** [comment]
ツイッターでも話してましたが、完成するまでは大変だと思いますが、コマンドとして使いやすくすると後々便利なのでよろしくお願いします。

**Comment by ab25cq** [comment]
了解です。ちょっと今から動くようにしてみます。

**Comment by hsk** [comment]
cd examples
clover2 Hello2.cl
でうまく動きました！

**Comment by hsk** [comment]
cd examples
clover2 dep_error.cl

だと固まります。Dep1.clclからDep2.clclを呼び出して、Dep2.clclからDep1.clclを呼び出しているので無限ループになっていると思います。

**Comment by ab25cq** [comment]
了解です。アルゴリズム考えます。スタックさせればいいですね。

**Comment by ab25cq** [comment]
修正しました。includeが必要になりますが、、、。（単に一つのソースファイルとしてコンパイルしているだけですw

**Comment by hsk** [comment]
ありがとうございます。
完成ということで閉じます。
